import { StyleSheet } from "react-native-unistyles";

export const styles = StyleSheet.create((theme) => ({
  stack: { gap: theme.spacing.md },
  stackTight: { gap: theme.spacing.sm },
  profileHeader: { gap: theme.spacing.xs },
  personName: { color: theme.colors.text, fontSize: 26, fontWeight: "800", letterSpacing: -0.6 },
  intro: { color: theme.colors.text, fontSize: 16, lineHeight: 24 },
  statusText: { color: theme.colors.primary, fontSize: 14, fontWeight: "700", lineHeight: 20 },
  actionRow: { flexDirection: "row", gap: theme.spacing.sm },
  actionGrow: { flex: 1 },
  pressableCard: { borderRadius: 20 },
  postMeta: { flexDirection: "row", justifyContent: "space-between" },
  postTitle: { color: theme.colors.text, fontSize: 18, fontWeight: "800", letterSpacing: -0.3 },
  postBody: { color: theme.colors.muted, fontSize: 15, lineHeight: 22 },
  detailBody: { color: theme.colors.text, fontSize: 16, lineHeight: 25 },
  guide: { color: theme.colors.muted, fontSize: 15, lineHeight: 22 },
  composer: { gap: theme.spacing.sm, paddingBottom: theme.spacing.md },
  input: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    color: theme.colors.text,
    fontSize: 16,
    minHeight: 52,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 13,
  },
  inputLarge: { minHeight: 150 },
  roomRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: theme.spacing.md,
    justifyContent: "space-between",
  },
  roomText: { flex: 1, gap: theme.spacing.xs },
  unreadText: { color: theme.colors.primary, fontSize: 13, fontWeight: "700", textAlign: "right" },
  messageMine: { alignItems: "flex-end", gap: theme.spacing.xs },
  messageOther: { alignItems: "flex-start", gap: theme.spacing.xs },
  bubbleMine: {
    backgroundColor: theme.colors.primary,
    borderRadius: 18,
    maxWidth: "84%",
    padding: theme.spacing.md,
  },
  bubbleOther: {
    backgroundColor: theme.colors.surfaceSoft,
    borderRadius: 18,
    maxWidth: "84%",
    padding: theme.spacing.md,
  },
  bubbleMineText: { color: theme.colors.primaryText, fontSize: 16, lineHeight: 22 },
  bubbleOtherText: { color: theme.colors.text, fontSize: 16, lineHeight: 22 },
  messageMeta: { alignItems: "center", flexDirection: "row", gap: theme.spacing.xs },
  formLabel: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  formLabelText: { color: theme.colors.text, fontSize: 16, fontWeight: "700" },
  choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm },
  choice: {
    backgroundColor: theme.colors.surfaceSoft,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  choiceSelected: { backgroundColor: theme.colors.primary },
  choiceText: { color: theme.colors.text, fontSize: 15, fontWeight: "700" },
  choiceTextSelected: { color: theme.colors.primaryText },
}));
