export const FIRST_MESSAGE_MAX_LENGTH = 30;

export const MESSAGE_MAX_LENGTH = 90;

export const CHAT_PAGE_SIZE = 100;
export const CHAT_POLL_INTERVAL_MS = 8_000;
export const CHAT_START_REACHED_THRESHOLD = 0.2;
export const ROOM_ROW_ESTIMATED_HEIGHT = 73;
